<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <Import Project="../../../Version.props"/>

  <ItemGroup>
    <Page Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Styles\FrameDemoCtl.xaml" Link="UserControl\Styles\FrameDemoCtl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Styles\FrameDemoCtl.xaml.cs" Link="UserControl\Styles\FrameDemoCtl.xaml.cs">
      <DependentUpon>UserControl\Styles\FrameDemoCtl.xaml</DependentUpon>
    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Tools\Converter\StringRepeatConverter.cs" Link="Tools\Converter\StringRepeatConverter.cs">
    </Compile>
  </ItemGroup>
</Project>
