<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <Import Project="../../../Version.props"/>

  <ItemGroup>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\LangProvider.cs">
      <Link>Properties\Langs\LangProvider.cs</Link>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>LangProvider.tt</DependentUpon>
    </Compile>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.Designer.cs">
      <Link>Properties\Langs\Lang.Designer.cs</Link>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Lang.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\App.config">
      <Link>Properties\App.config</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Tools\Extension\LangExtension.cs">
      <Link>Tools\Extension\LangExtension.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.tr.resx">
      <Link>Properties\Langs\Lang.tr.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.ca-ES.resx">
      <Link>Properties\Langs\Lang.ca-ES.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.cs.resx">
      <Link>Properties\Langs\Lang.cs.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.en.resx">
      <Link>Properties\Langs\Lang.en.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.es.resx">
      <Link>Properties\Langs\Lang.es.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.fa.resx">
      <Link>Properties\Langs\Lang.fa.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.fr.resx">
      <Link>Properties\Langs\Lang.fr.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.ja.resx">
      <Link>Properties\Langs\Lang.ja.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.ko-KR.resx">
      <Link>Properties\Langs\Lang.ko-KR.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.pt-BR.resx">
      <Link>Properties\Langs\Lang.pt-BR.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.pl.resx">
      <Link>Properties\Langs\Lang.pl.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.ru.resx">
      <Link>Properties\Langs\Lang.ru.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.resx">
      <Link>Properties\Langs\Lang.resx</Link>
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Lang.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>


  <ItemGroup>
    <Page Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Styles\FlowDocumentDemoCtl.xaml" Link="UserControl\Styles\FlowDocumentDemoCtl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Styles\FlowDocumentDemoCtl.xaml.cs" Link="UserControl\Styles\FlowDocumentDemoCtl.xaml.cs">
      <DependentUpon>UserControl\Styles\FlowDocumentDemoCtl.xaml</DependentUpon>
    </Compile>

  </ItemGroup>

</Project>
