<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <Import Project="../../../Version.props" />

  <PropertyGroup>
    <AssemblyName>HandyControlDemo</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Data\MessageToken.cs">
      <Link>Data\MessageToken.cs</Link>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>MessageToken.tt</DependentUpon>
    </Compile>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\LangProvider.cs">
      <Link>Properties\Langs\LangProvider.cs</Link>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>LangProvider.tt</DependentUpon>
    </Compile>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.Designer.cs">
      <Link>Properties\Langs\Lang.Designer.cs</Link>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Lang.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\App.config">
      <Link>Properties\App.config</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Tools\Extension\LangExtension.cs">
      <Link>Tools\Extension\LangExtension.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.tr.resx">
      <Link>Properties\Langs\Lang.tr.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.ca-ES.resx">
      <Link>Properties\Langs\Lang.ca-ES.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.cs.resx">
      <Link>Properties\Langs\Lang.cs.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.en.resx">
      <Link>Properties\Langs\Lang.en.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.es.resx">
      <Link>Properties\Langs\Lang.es.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.fa.resx">
      <Link>Properties\Langs\Lang.fa.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.fr.resx">
      <Link>Properties\Langs\Lang.fr.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.ja.resx">
      <Link>Properties\Langs\Lang.ja.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.ko-KR.resx">
      <Link>Properties\Langs\Lang.ko-KR.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.pt-BR.resx">
      <Link>Properties\Langs\Lang.pt-BR.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.pl.resx">
      <Link>Properties\Langs\Lang.pl.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.ru.resx">
      <Link>Properties\Langs\Lang.ru.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.resx">
      <Link>Properties\Langs\Lang.resx</Link>
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Lang.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Page Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Controls\ImageSelectorDemoCtl.xaml" Link="UserControl\Controls\ImageSelectorDemoCtl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Controls\ImageSelectorDemoCtl.xaml.cs" Link="UserControl\Controls\ImageSelectorDemoCtl.xaml.cs">
      <DependentUpon>UserControl\Controls\ImageSelectorDemoCtl.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\..\Shared\HandyControlDemo_Shared\Resources\Img\icon.ico">
      <Link>Resources\Img\icon.ico</Link>
    </Resource>
    <Resource Include="..\..\..\Shared\HandyControlDemo_Shared\Resources\Img\cloud.png">
      <Link>Resources\Img\cloud.png</Link>
    </Resource>

    <Resource Include="..\..\..\Shared\HandyControlDemo_Shared\Resources/fabric-icons.ttf">
      <Link>Resources/fabric-icons.ttf</Link>
    </Resource>

    <Page Include="..\..\..\Shared\HandyControlDemo_Shared\Resources\Themes\Styles\Style.xaml">
      <Link>Resources\Themes\Styles\Style.xaml</Link>
    </Page>
    <Resource Include="..\..\..\Shared\HandyControlDemo_Shared\Resources\Themes\Basic\Fonts.xaml">
      <Link>Resources\Themes\Basic\Fonts.xaml</Link>
    </Resource>
    <Resource Include="..\..\..\Shared\HandyControlDemo_Shared\Resources\Themes\Basic\Brushes.xaml">
      <Link>Resources\Themes\Basic\Brushes.xaml</Link>
    </Resource>
    <Resource Include="..\..\..\Shared\HandyControlDemo_Shared\Resources\Themes\Basic\Geometries.xaml">
      <Link>Resources\Themes\Basic\Geometries.xaml</Link>
    </Resource>
  </ItemGroup>

  <ItemGroup>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Data\Enum\DemoType.cs" Link="Data\Enum\DemoType.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\ViewModel\DemoViewModelBase`1.cs" Link="ViewModel\DemoViewModelBase`1.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Service\Data\DataService.cs" Link="Service\Data\DataService.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Data\Model\DemoDataModel.cs" Link="Data\Model\DemoDataModel.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Data\Model\DemoInfoModel.cs" Link="Data\Model\DemoInfoModel.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Data\Model\DemoItemModel.cs" Link="Data\Model\DemoItemModel.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\ViewModel\Main\MainViewModel.cs" Link="ViewModel\Main\MainViewModel.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Data\Model\AvatarModel.cs" Link="Data\Model\AvatarModel.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Data\Model\CardModel.cs" Link="Data\Model\CardModel.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Data\Model\ChatInfoModel.cs" Link="Data\Model\ChatInfoModel.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Data\Model\StepBarDemoModel.cs" Link="Data\Model\StepBarDemoModel.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Data\Model\CoverViewDemoModel.cs" Link="Data\Model\CoverViewDemoModel.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Data\Model\TabControlDemoModel.cs" Link="Data\Model\TabControlDemoModel.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Data\Model\PropertyGridDemoModel.cs" Link="Data\Model\PropertyGridDemoModel.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Tools\Helper\AssemblyHelper.cs" Link="Tools\Helper\AssemblyHelper.cs">

    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Basic\IFull.cs">
      <Link>UserControl\Basic\IFull.cs</Link>
    </Compile>
  </ItemGroup>
</Project>
