<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <AssemblyName>HandyControlDemo</AssemblyName>
  </PropertyGroup>

  <Import Project="../../../Version.props"/>

  <ItemGroup>
    <Page Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Styles\BrushDemoCtl.xaml" Link="UserControl\Styles\BrushDemoCtl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Styles\BrushDemoCtl.xaml.cs" Link="UserControl\Styles\BrushDemoCtl.xaml.cs">
      <DependentUpon>UserControl\Styles\BrushDemoCtl.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
