<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <AssemblyName>HandyControlDemo</AssemblyName>
    <RootNamespace>HandyControlDemo</RootNamespace>
    <TargetFrameworks>netcoreapp3.0;netcoreapp3.1;net45;net451;net452;net46;net461;net462;net47;net471;net472;net48;net481;net5.0-windows;net6.0-windows;net7.0-windows;net8.0-windows</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ApplicationManifest>..\..\..\Shared\HandyControlDemo_Shared\app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup Condition="$(TargetFramework.StartsWith('net4'))">
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HandyControl" Version="3.5.0" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="MvvmLightLibsStd10" Version="5.4.1.1" />
    <!--<PackageReference Include="MvvmLightLibs" Version="5.4.1.1" />-->
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\LangProvider.cs">
      <Link>Properties\Langs\LangProvider.cs</Link>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>LangProvider.tt</DependentUpon>
    </Compile>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.Designer.cs">
      <Link>Properties\Langs\Lang.Designer.cs</Link>
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Lang.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\App.config">
      <Link>Properties\App.config</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Tools\Extension\LangExtension.cs">
      <Link>Tools\Extension\LangExtension.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.tr.resx">
      <Link>Properties\Langs\Lang.tr.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.ca-ES.resx">
      <Link>Properties\Langs\Lang.ca-ES.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.cs.resx">
      <Link>Properties\Langs\Lang.cs.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.en.resx">
      <Link>Properties\Langs\Lang.en.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.es.resx">
      <Link>Properties\Langs\Lang.es.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.fa.resx">
      <Link>Properties\Langs\Lang.fa.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.fr.resx">
      <Link>Properties\Langs\Lang.fr.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.ja.resx">
      <Link>Properties\Langs\Lang.ja.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.ko-KR.resx">
      <Link>Properties\Langs\Lang.ko-KR.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.pt-BR.resx">
      <Link>Properties\Langs\Lang.pt-BR.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.pl.resx">
      <Link>Properties\Langs\Lang.pl.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.ru.resx">
      <Link>Properties\Langs\Lang.ru.resx</Link>
    </EmbeddedResource>
    <EmbeddedResource Include="..\..\..\Shared\HandyControlDemo_Shared\Properties\Langs\Lang.resx">
      <Link>Properties\Langs\Lang.resx</Link>
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Lang.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>


  <ItemGroup>
    <Page Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Styles\BorderDemoCtl.xaml" Link="UserControl\Styles\BorderDemoCtl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Styles\BorderDemoCtl.xaml.cs" Link="UserControl\Styles\BorderDemoCtl.xaml.cs">
      <DependentUpon>UserControl\Styles\BorderDemoCtl.xaml</DependentUpon>
    </Compile>

    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\Tools\Converter\StringRepeatConverter.cs" Link="Tools\Converter\StringRepeatConverter.cs">
    </Compile>
  </ItemGroup>
</Project>
