<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <Import Project="../../../Version.props"/>

  <ItemGroup>
    <Page Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Styles\NativeProgressBarDemoCtl.xaml" Link="UserControl\Styles\NativeProgressBarDemoCtl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Compile Include="..\..\..\Shared\HandyControlDemo_Shared\UserControl\Styles\NativeProgressBarDemoCtl.xaml.cs" Link="UserControl\Styles\NativeProgressBarDemoCtl.xaml.cs">
      <DependentUpon>UserControl\Styles\NativeProgressBarDemoCtl.xaml</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
